input-data:
  file:
    enable: ${input-directory-enable:false}
    directory: ${input-directory-path:}
    path: ${input-file-path:}
logging:
  level:
#    root: debug
    com.hupalo.watchapi: debug

management.endpoint.restart.enabled: ${input-data.file.enable}
